module ParagraphTest exposing (suite)

import Expect
import Test exposing (..)
import Translate.Paragraph as Paragraph


suite : Test
suite =
    describe "Paragraph"
        [ test "convert paragraph to lines" <|
            \() ->
                Paragraph.toLines "O dicionário italiano reconhece a palavra felliniano. Significa quase tudo o que tem a ver com o Mago de Rimini e seu cinema, não há dúvida. Mas é também o adjetivo que descreve um universo estético, social e político que impregna uma nação inteira há seis décadas. A tensão entre o homem moderno e os rudimentos do passado, os sonhos eróticos, o machismo caricatural ou uma estranha mistura de crítica e paixão simultânea por uma sociedade do espetáculo que acabou se tornando uma odiosa indústria publicitária. Federico Fellini (Rimini, 1920-Roma, 1993) ganhou cinco Oscars, deixou alguns dos filmes mais insólitos produzidos na Itália e fundou uma nova maneira de contar o mundo a partir dos sonhos e do lado mais grotesco de suas próprias memórias. Um século depois de seu nascimento, o big bang estético criado durante os anos em que viveu em Roma arrebenta as costuras do dicionário. "
                    |> Expect.equal
                        [ "O dicionário italiano reconhece a palavra felliniano"
                        , "Significa quase tudo o que tem a ver com o Mago de Rimini e seu cinema, não há dúvida"
                        , "Mas é também o adjetivo que descreve um universo estético, social e político que impregna uma nação inteira há seis décadas"
                        , "A tensão entre o homem moderno e os rudimentos do passado, os sonhos eróticos, o machismo caricatural ou uma estranha mistura de crítica e paixão simultânea por uma sociedade do espetáculo que acabou se tornando uma odiosa indústria publicitária"
                        , "Federico Fellini (Rimini, 1920-Roma, 1993) ganhou cinco Oscars, deixou alguns dos filmes mais insólitos produzidos na Itália e fundou uma nova maneira de contar o mundo a partir dos sonhos e do lado mais grotesco de suas próprias memórias"
                        , "Um século depois de seu nascimento, o big bang estético criado durante os anos em que viveu em Roma arrebenta as costuras do dicionário"
                        ]
        , test "are paragraphs equivalent" <|
            \() ->
                Paragraph.areParagraphsEquivalent "O dicionário italiano reconhece a palavra felliniano. Significa quase tudo o que tem a ver com o Mago de Rimini e seu cinema, não há dúvida. Mas é também o adjetivo que descreve um universo estético, social e político que impregna uma nação inteira há seis décadas. A tensão entre o homem moderno e os rudimentos do passado, os sonhos eróticos, o machismo caricatural ou uma estranha mistura de crítica e paixão simultânea por uma sociedade do espetáculo que acabou se tornando uma odiosa indústria publicitária. Federico Fellini (Rimini, 1920-Roma, 1993) ganhou cinco Oscars, deixou alguns dos filmes mais insólitos produzidos na Itália e fundou uma nova maneira de contar o mundo a partir dos sonhos e do lado mais grotesco de suas próprias memórias. Um século depois de seu nascimento, o big bang estético criado durante os anos em que viveu em Roma arrebenta as costuras do dicionário. " "El diccionario italiano reconoce la palabra felliniano. Significa casi todo aquello que tiene que ver con el Mago de Rímini y su cine, no alberga dudas. Pero también es el adjetivo que describe un universo estético, social y político que ha impregnado a toda una nación desde hace seis décadas. La tensión entre el hombre moderno y los rudimentos del pasado, los sueños eróticos, el machismo caricaturesco o una extraña mezcla de crítica y enamoramiento simultáneo hacia una sociedad del espectáculo que terminó convertida en odiosa industria publicitaria. Federico Fellini (Rímini, 1920-Roma, 1993) ganó cinco Oscar, dejó algunas de las películas más asombrosas producidas en Italia y fundó una nueva manera de contar el mundo desde los sueños y el lado más grotesco de sus propios recuerdos. Un siglo después de su nacimiento, el big bang estético creado durante los años que vivió en Roma revienta las costuras del diccionario." |> Expect.true "Expect paragraphs to be equivalent"
        , test "are articles equivalent" <|
            \() ->
                Paragraph.areArticleBodyEquivalent
                    [ "El diccionario italiano reconoce la palabra felliniano. Significa casi todo aquello que tiene que ver con el Mago de Rímini y su cine, no alberga dudas. Pero también es el adjetivo que describe un universo estético, social y político que ha impregnado a toda una nación desde hace seis décadas. La tensión entre el hombre moderno y los rudimentos del pasado, los sueños eróticos, el machismo caricaturesco o una extraña mezcla de crítica y enamoramiento simultáneo hacia una sociedad del espectáculo que terminó convertida en odiosa industria publicitaria. Federico Fellini (Rímini, 1920-Roma, 1993) ganó cinco Oscar, dejó algunas de las películas más asombrosas producidas en Italia y fundó una nueva manera de contar el mundo desde los sueños y el lado más grotesco de sus propios recuerdos. Un siglo después de su nacimiento, el big bang estético creado durante los años que vivió en Roma revienta las costuras del diccionario."
                    , "Una placa en el número 110 de la silenciosa via Margutta, entre la piazza de Spagna y la Villa Borghese, recuerda el lugar donde vivió durante décadas Fellini con su esposa, Giulietta Masina. La casa se vació y se vendió en 1994 cuando ella murió y hoy pertenece a otro propietario. Pero los confines de aquel mundo más prosaico y rutinario, hecho de paseos, discusiones con los sospechosos habituales como Ennio Flaiano —escritor, periodista y guionista/ventrílocuo de sus mejores películas— o largas comidas con Marcello Mastroianni no se expandían tanto como su imaginación. Cada mañana tomaba café en el Canova y se dejaba caer para comer en Dal Toscano en el barrio de Prati, siempre en la misma mesa."
                    , "Roma fue el lugar que esculpió a un chico que llegó con 18 años buscando fortuna como viñetista y dibujante desde Rímini. La ciudad de la costa adriática de tejados rojos y estanqueras voluptuosas fue un enjambre de recuerdos mágicos e inconexos que logró recopilar en Amarcord (1973), también en I Vitelloni (Los inútiles, 1953) o en La Strada (1954). La verdadera patria de Fellini, sin embargo, la que jamás tuvo fronteras, supo mantenerse oculta entre las cuatro paredes del Teatro 5 de Cinecittà, donde construyó la mayoría de sus ensoñaciones."
                    , "Ese melancólico Hollywood italiano, al final de la via Tuscolana, en la otra punta de Roma, intenta recuperar el vigor con nuevos rodajes. La casa de Fellini, el estudio que ardió en 2012 y en el que muchos no quisieron rodar intimidados por viejos fantasmas, ha estado ocupada hasta hace poco por los decorados de El nuevo Papa, la serie vaticana de Sorrentino, puede que el mayor heredero —imitador, mascullan algunos en Italia— del cineasta de Rímini. Aquí se rodaron Ocho y medio (1963), La Dolce Vita (1960), Las noches de Cabiria (1958)… también algunos de los últimos filmes, como Y la nave va (1983) y Ginger y Fred (1986), en la que comenzó su relación con el diseñador de vestuario Maurizio Millenotti. “El set de rodaje era su hogar. Le encantaba estar ahí porque amaba a la familia del cine. Adoraba estar en medio de los maquinistas, electricistas, iluminadores... Tenía una relación particular e individual con todos. Por aquí pasaron reyes, grandes cineastas como Scorsese, políticos de todo tipo… Todos querían verle trabajar en su espacio. Cuando comíamos fuera siempre contaba anécdotas apasionantes y le escuchábamos como niños”, recuerda al teléfono el diseñador."
                    , "La última media hora de Ginger y Fred transcurre en un plató con una orquesta casi siempre presente. Nicola Piovani —que se llevó un Oscar por La vida es bella en 1997— se encargó de la partitura y remplazó al histórico Nino Rota, de quien había aprendido y cuya línea nunca quiso traicionar en los siguientes filmes. “Durante aquella película viví casi tres semanas ahí. Fellini me hacía improvisar músicas en un pequeño piano vertical amplificado. Me daba indicaciones veloces, alocadamente… yo improvisaba y la orquesta, escuchando, venía detrás simulando los movimientos más representativos. Fueron días inolvidables”, recuerda Piovani, que después de aquella experiencia escribió también la partitura de La voz de la luna (1990)."
                    , "Unas escaleras de hierro del Teatro 5 conducen a una especie de balcón trasero donde puede divisarse, junto a un pedazo de la antigua Roma de cartón piedra, el plató y decorado de Gran Hermano VIP. Una frontera entre los sueños y lo grotesco que hoy funciona como involuntario homenaje al universo de un artista que vivió en los últimos años obsesionado con la televisión y los efectos del mundo imaginario de la publicidad en la salud mental de los italianos. “La mirada felliniana es, en realidad, una mirada anticipatoria. El impacto de su obra ha sido enorme, una lección incorporada de forma inconsciente por la cultura italiana. También en la política, especialmente de Berlusconi en adelante. Él es esa figura típica de Italia que muestra la relación entre la modernidad y la tradición. Hoy el país se parece mucho al que él imaginó. Pero cuidado, sin gracia, sin poesía, carente de fantasía y de esa nostalgia”, señala el escritor y periodista Filippo Ceccarelli."
                    , "El día que murió Fellini, el 31 de octubre de 1993, Berlusconi lanzaba el logotipo de Forza Italia. Casualidad o no, el cineasta pasó los últimos años obsesionado con Il Cavaliere y llegó a escribir un guion que nunca se rodó sobre una Venecia distópica convertida por el magnate en un plató para rodar anuncios: el gran Canal pasaría a llamarse Canale 5 (por Tele 5). A diferencia de otros cineastas coetáneos como Pier Paolo Pasolini, mantuvo siempre una mirada crítica, pero desideologizada y desvinculada, pese a su gran amistad con Giulio Andreotti, de las corrientes políticas. “Era amigo de todos y de nadie. Hacía brillantemente sus negocios y se mantenía fuera de los asuntos de partidos, no se pronunciaba. Podía parecer un director alejado de las tensiones, pero en realidad fue quien mejor entendió todo el contexto. El problema entonces no era la dictadura contra la clase obrera, o los estudiantes reclamando protagonismo… la cuestión verdadera era la del capitalismo en su extrema realización. Un fenómeno por el cual ya no hacía falta imponer las cosas, sino capturar la mente de la gente con la televisión. Y en esa interpretación Fellini fue mucho más político de lo que siempre se dijo”."
                    , "La verdad entre lo que se contó y el recuerdo de cómo fue realmente pertenece hoy a muy pocas personas. La actriz Sandra Milo trabajó con él en películas como Ocho y medio o Giulietta de los espíritus (1965) y fue su amante durante 17 años. Ambos se conocieron fugazmente una tarde de verano en un pinar de Fregene, a orillas del mar romano, cuando Fellini compartía mesa con Ennio Flaiano (mucho antes de que aquella relación terminase violentamente). “Ennio me llamó y me lo presentó. Quedé sobrecogida, era guapísimo, tenía un gran magnetismo… esos ojos tensos, curiosos, capaces de absorberte, pero de manera agradable, nada invasivo ni agresivo. En ese momento me enamoré de él, perdidamente, inevitable y fatalmente”, recuerda al teléfono Milo. No volvieron a verse hasta al cabo de dos años."
                    , "Milo acababa de empezar su carrera. Había rodado con Rossellini la película Vanina, Vanini (1961), destripada por la crítica, y condenatoria para ella. Cayó en el olvido y dejó el cine. Pero un día apareció el cineasta en su casa por la mañana, la sacó de la cama, le hizo una prueba y la contrató para hacer el papel de Carla, la amante de Marcello Mastroianni, reflejo de la vida del propio Fellini. Todo encajaba premonitoriamente una vez más. “Hoy muchos directores no quieren trabajar conmigo para que no haga comparaciones. Pero él era una persona muy especial. Tenía una capacidad increíble de hacerte sentir el predilecto, un modo mágico de entrar dentro de ti, entender exactamente quién eras, encontrar tu parte más preciosa y llevarla a la superficie para hacerte consciente de algo que ignorabas tener. Todos queríamos trabajar con él y que estuviese cerca. Tenía ese poder, un arte siempre a favor del ser humano, nunca en contra”."
                    , "La relación de Fellini y Milo solo terminó cuando él le propuso abandonar la clandestinidad y tener una vida juntos casi 20 años después de haberse conocido en aquella pineda. Ella se negó. Temía la corrosión de la rutina, las discusiones, no saber gestionar la normalidad con aquella persona tan extraordinaria... no volvieron a verse jamás. Pero el cineasta siempre volvió a Giulietta Masina. “Era una mujer maravillosa, inteligentísima, curiosa y culta. Ella sabía que era imposible tener una relación tradicional con Federico”."
                    , "Fellini no tuvo hijos. Masina y él perdieron al pequeño Pier Federico 11 días después de nacer. Su sobrina Francesca, única heredera de su legado, ocupó durante años ese lugar en la retaguardia sentimental de su tío. Ella tiene su propio Amarcord —“me acuerdo” en dialecto romañolo— sobre aquellos años en los que veía llegar a su tío convertido en una estrella internacional. “Volvía a Rímini a ver a su madre, a su hermana Maddalena, a mí… Tengo recuerdos muy ligados a la mesa. Giulietta cocinaba en Roma y mi madre en Rímini. Se empezaba con la piadina, un poco de parmesano, luego la pasta rellena con caldo. Y se cerraba con la sopa inglesa, su postre preferido. Todo el mundo quería saber cosas de él. Yo nunca me atreví a pedirle nada ni a interrogarle. ¿Qué le preguntaría hoy? Quizá le preguntaría si no hubiera preferido disfrutar más de su familia y de sus seres queridos, en lugar de estar permanentemente creando y trabajando. Le preguntaría si se arrepiente de no haber disfrutado más de su madre, de su hermano Riccardo, de mí... Era el genio creativo que cambió el cine, con cinco Oscar… pero supongo que siempre hay que pagar un precio”. Quizá esa fuera la parte menos felliniana de toda su vida."
                    ]
                    [ "O dicionário italiano reconhece a palavra felliniano. Significa quase tudo o que tem a ver com o Mago de Rimini e seu cinema, não há dúvida. Mas é também o adjetivo que descreve um universo estético, social e político que impregna uma nação inteira há seis décadas. A tensão entre o homem moderno e os rudimentos do passado, os sonhos eróticos, o machismo caricatural ou uma estranha mistura de crítica e paixão simultânea por uma sociedade do espetáculo que acabou se tornando uma odiosa indústria publicitária. Federico Fellini (Rimini, 1920-Roma, 1993) ganhou cinco Oscars, deixou alguns dos filmes mais insólitos produzidos na Itália e fundou uma nova maneira de contar o mundo a partir dos sonhos e do lado mais grotesco de suas próprias memórias. Um século depois de seu nascimento, o big bang estético criado durante os anos em que viveu em Roma arrebenta as costuras do dicionário."
                    , "Uma placa no número 110 da silenciosa Via Margutta, entre a Piazza de Spagna e a Villa Borghese, lembra o lugar onde Fellini viveu durante décadas com a esposa Giulietta Masina. A casa foi esvaziada e vendida em 1994, quando ela morreu, e hoje pertence a outro proprietário. Mas os confins daquele mundo mais prosaico e rotineiro, feito de passeios, discussões com os suspeitos habituais, como Ennio Flaiano —escritor, jornalista e roteirista/ventríloquo de seus melhores filmes— ou longas refeições com Marcello Mastroianni não se expandiam tanto quanto sua imaginação. Todas as manhãs tomava café no Canova e aparecia para comer no Dal Toscano, no bairro de Prati, sempre na mesma mesa."
                    , "Roma foi o lugar que esculpiu um rapaz que chegou de Rimini com 18 anos em busca de fortuna como cartunista e desenhista. A cidade da costa adriática de telhados vermelhos e vendedoras de cigarro voluptuosas era um enxame de lembranças mágicas e desconexas que conseguiu recopilar em Amarcord (1973), também em I Vitelloni (Os Boas-vidas, 1953) e em A Estrada da Vida (1954). A verdadeira pátria de Fellini, no entanto, a que nunca teve fronteiras, ele soube manter escondida entre as quatro paredes do Estúdio 5 de Cinecittà, onde construiu a maioria dos seus devaneios."
                    , "Essa melancólica Hollywood italiana, no final da Via Tuscolana, do outro lado de Roma, tenta recuperar o vigor com novas rodagens. A casa de Fellini, o estúdio que pegou fogo em 2012 e no qual muitos não quiseram filmar intimidados por velhos fantasmas, esteve ocupada até recentemente pelos cenários de O Novo Papa, a série sobre o Vaticano de Sorrentino, talvez o maior herdeiro —imitador, resmungam alguns na Itália— do cineasta de Rimini. Aqui foram rodados Oito e Meio (1963), A Doce Vida (1960), Noites de Cabíria (1958)... e também alguns dos últimos filmes, como E La Nave Va (1983) e Ginger e Fred (1986), no qual começou sua relação com o figurinista Maurizio Millenotti. “O set de filmagem era a casa dele. Adorava estar lá porque amava a família do cinema. Adorava estar no meio dos maquinistas, eletricistas, iluminadores... Tinha uma relação particular e individual com todos. Por aqui passaram reis, grandes cineastas como Scorsese, políticos de todo tipo... Todos queriam vê-lo trabalhar em seu espaço. Quando comíamos fora, sempre contava histórias emocionantes e o ouvíamos como crianças”, lembra o figurinista em uma conversa por telefone."
                    , "A última meia hora de Ginger e Fred acontece em um cenário com uma orquestra quase sempre presente. Nicola Piovani —que ganhou um Oscar por A Vida É Bela em 1997— foi o encarregado da trilha sonora e substituiu o histórico Nino Rota, de quem tinha aprendido e cuja linha nunca quis trair nos filmes seguintes. “Durante esse filme morei quase três semanas lá. Fellini me fazia improvisar músicas em um pequeno piano vertical amplificado. Me dava instruções rápidas de um jeito meio maluco... eu improvisava e a orquestra, ouvindo, vinha atrás simulando os movimentos mais representativos. Foram dias inesquecíveis”, lembra Piovani, que depois dessa experiência também escreveu a partitura de A Voz da Lua (1990)."
                    , "As escadas de ferro do Estúdio 5 levam a uma espécie da varanda traseira de onde se pode ver, ao lado de um pedaço da Roma Antiga de papelão, o estúdio e o cenário do Grande Fratello VIP [versão italiana do Big Brother]. Uma fronteira entre os sonhos e o grotesco que hoje funciona como homenagem involuntária ao universo de um artista que viveu seus últimos anos obcecado pela televisão e pelos efeitos do mundo imaginário da publicidade na saúde mental dos italianos. “O olhar felliniano é, na verdade, um olhar premonitório. O impacto de sua obra foi enorme, uma lição incorporada de forma inconsciente pela cultura italiana. Também na política, especialmente a partir de Berlusconi. Ele é essa figura típica da Itália que mostra a relação entre a modernidade e a tradição. Hoje o país se parece muito a como ele o imaginou. Mas cuidado, sem graça, sem poesia, desprovido de fantasia e dessa nostalgia”, afirma o escritor e jornalista Filippo Ceccarelli."
                    , "No dia em que Fellini morreu, 31 de outubro de 1993, Berlusconi lançou o logotipo do Forza Italia. Por acaso ou não, o cineasta passou os últimos anos obcecado por Il Cavaliere e chegou a escrever um roteiro que nunca foi filmado sobre uma Veneza distópica transformada pelo magnata em um cenário para filmar anúncios: o Grande Canal passaria a se chamar como Canale 5 [referência ao nome da emissora de televisão de Berlusconi]. Ao contrário de outros cineastas de sua geração, como Pier Paolo Pasolini, sempre manteve um olhar crítico, mas desideologizado e desvinculado, apesar de sua grande amizade com Giulio Andreotti, em relação às correntes políticas. “Era amigo de todos e de ninguém. Fazia seus negócios de maneira brilhante e ficava fora dos assuntos de partidos, não se pronunciava. Podia parecer um diretor distante das tensões, mas, na realidade, foi quem melhor entendeu todo o contexto. O problema então não era a ditadura contra a classe operária, ou os estudantes reivindicando protagonismo... a verdadeira questão era a do capitalismo em sua extrema realização. Um fenômeno para o qual não era mais necessário impor as coisas, mas capturar a mente das pessoas com a televisão. E nessa interpretação Fellini foi muito mais político do que sempre se disse”."
                    , "A verdade entre o que se contou e a memória de como realmente foi pertence hoje a muito poucas pessoas. A atriz Sandra Milo trabalhou com ele em filmes como Oito e Meio ou Julieta dos Espíritos (1965) e foi sua amante durante 17 anos. Ambos se conheceram rapidamente numa tarde de verão em um pinheiral de Fregene, às margens do mar romano, quando Fellini dividia uma mesa com Ennio Flaiano (muito antes de essa relação terminar violentamente). “Ennio me chamou e me apresentou a ele. Fiquei impressionada, era muito bonito, tinha um grande magnetismo... aqueles olhos tensos, curiosos, capazes de te absorver, mas de uma maneira agradável, nada invasivo ou agressivo. Naquele momento eu me apaixonei por ele, perdidamente, inevitavelmente e fatalmente”, lembra Milo ao telefone. Só se viram novamente dois anos depois."
                    , "Milo tinha acabado de começar sua carreira. Havia rodado com Rossellini o filme Vanina Vanini (1961), arrasado pela crítica e condenatório para ela. Caiu no esquecimento e abandonou o cinema. Mas um dia o cineasta apareceu na casa dela de manhã, tirou-a da cama, fez um teste e a contratou para fazer o papel de Carla, a amante de Marcello Mastroianni, reflexo da vida do próprio Fellini. Tudo se encaixava premonitoriamente mais uma vez. “Hoje muitos diretores não querem trabalhar comigo para que eu não faça comparações. Mas ele era uma pessoa muito especial. Tinha uma capacidade incrível de fazer você se sentir o predileto, uma maneira mágica de entrar dentro de você, entender exatamente quem você era, encontrar sua parte mais preciosa e trazê-la à superfície para te tornar consciente de algo que você não sabia que tinha. Todos nós queríamos trabalhar com ele e que estivesse perto. Ele tinha esse poder, uma arte sempre a favor do ser humano, nunca contra”."
                    , "O relacionamento entre Fellini e Milo só terminou quando ele propôs abandonar a clandestinidade e ter uma vida juntos quase 20 anos depois de terem se conhecido naquele pinheiral. Ela recusou. Temia a corrosão da rotina, as discussões, não saber administrar a normalidade com aquela pessoa tão extraordinária... nunca mais se viram. Mas o cineasta sempre voltava para Giulietta Masina. “Era uma mulher maravilhosa, inteligente, curiosa e culta. Ela sabia que era impossível ter um relacionamento tradicional com Federico.”"
                    , "Fellini não teve filhos. Ele e Masina perderam o pequeno Pier Federico 11 dias depois do nascimento. Sua sobrinha Francesca, a única herdeira de seu legado, ocupou durante anos esse lugar na retaguarda sentimental do tio. Ela tem seu próprio Amarcord —“eu me lembro” no dialeto romanholo— sobre aqueles anos em que viu seu tio se tornar uma estrela internacional. “Voltava a Rimini para ver a mãe, sua irmã Maddalena, eu... Tenho lembranças muito ligadas à mesa. Giulietta cozinhava em Roma e minha mãe em Rimini. Começava-se com a piadina, um pouco de parmesão, depois a massa recheada com caldo. E se terminava com a sopa inglesa, sua sobremesa favorita. Todo mundo queria saber dele. Eu nunca ousei pedir algo a ele ou questioná-lo. O que você perguntaria hoje e ele? Talvez se ele não tivesse preferido curtir mais a família e seus entes queridos, em vez de estar permanentemente criando e trabalhando. Eu perguntaria se ele se arrepende de não ter curtido mais a mãe, o irmão Riccardo, a mim... Era o gênio criativo que mudou o cinema, com cinco Oscars... mas acho que sempre se tem de pagar um preço”. Talvez essa fosse a parte menos felliniana de sua vida."
                    ]
                    |> Expect.true "Expect articles to be equivalent"
        ]
